---
title: "Pedagogy"
author: "Joshua Cabrera"
date: "2024-02-14"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidyverse)
library(caret)
library(GGally) #pairs plot
library(car) #added variable plots
library(MASS) #standardized Residuals
library(lmtest) #bp test
library(multcomp) #generalized linear hypothesis test
library(nlme)
library(tidyverse)
data  <- read_delim('ClassAssessment.txt')
data_copy <- data
data$Semester <- as.factor(data$Semester)

```


```{r }
ggplot(data = data, mapping = aes(x = Exam1, y = Final)) +
  geom_point()+
  # geom_smooth( se = FALSE)+
  labs(title = "Boxplot of Exam1 by Final",
       x = "Exam1",
       y = "Final")


ggplot(data = data, mapping = aes(x = Exam2, y = Final)) +
  geom_point()+
  # geom_smooth( se = FALSE)+
  labs(title = "Boxplot of Exam2 by Final",
       x = "Exam2",
       y = "Final")

ggplot(data = data, mapping = aes(x = Exam3, y = Final)) +
  geom_point()+
  # geom_smooth( se = FALSE)+
  labs(title = "Boxplot of Exam3 by Final",
       x = "Exam3",
       y = "Final")

ggplot(data = data, mapping = aes(x = HW, y = Final)) +
  geom_point()+
  # geom_smooth( se = FALSE)+
  labs(title = "Boxplot of HW by Final",
       x = "HW",
       y = "Final")

ggplot(data = data, mapping = aes(x = Quiz, y = Final)) +
  geom_point()+
  # geom_smooth( se = FALSE)+
  labs(title = "Boxplot of Quiz by Final",
       x = "Quiz",
       y = "Final")


ggplot(data = data, mapping = aes(x = NStudents, y = Final)) +
  geom_point()+
  # geom_smooth( se = FALSE)+
  labs(title = "Boxplot of NStudents by Final",
       x = "NStudents",
       y = "Final")


ggplot(data, aes(x = Semester, y = Final, fill = Semester)) +
  geom_boxplot() +
  labs(x = "Semester", y = "Final", title = "Box Plot Example") +
  theme_minimal()
```

```{r}

data_long <- data_copy %>%
  pivot_longer(
    cols = c(Exam1, Exam2, Exam3,HW,Quiz, Final) )

data_copy$id <- 1:30

data_long$factor_column <- factor(data_long$name)
data_long$factor_column <- factor(data_long$name, levels = c("Exam1", "Exam2", "Exam3", "HW", "Quiz", "Final"))

levels(data_long$factor_column)

# head(data_long)
ggplot(data_long, aes(x = name, y = value, group = id, colour = id))+
  geom_point()+
  geom_line()
```


```{r}
# summary(data)



# Pedagogy_lm <- lm(Final ~ ., data = data)
Pedagogy_lm <- lm(Final ~ ., data = data)
summary(Pedagogy_lm)

#Checking if our model should use NStudents and Semester
Pedagogy_lm_reduced <- lm(Final ~ Exam1+Exam2+Exam3+HW+Quiz, data = data)
summary(Pedagogy_lm_reduced)
anova(Pedagogy_lm_reduced,Pedagogy_lm)

#using reduced model and changing name
Pedagogy_lm <- lm(Final ~ Exam1+Exam2+Exam3+HW+Quiz, data = data)
summary(Pedagogy_lm)


data_copy$fittedVals <- Pedagogy_lm$fitted.values
data_copy$Residuals <- Pedagogy_lm$residuals

# write.csv(data, file = "ClassAssessment_copy.txt", row.names =T)

#none of the semesters performed better than other semesters
anova_result <- aov(lm(Final ~ Semester, data = data))
anova_result
summary(anova_result)
# anova_result <- anova(lm(value ~ group, data = df))

```


```{r}
bptest(Pedagogy_lm)

```


```{r}

```

# GLS model
```{r}
source("predictgls.R")

# Maybe switch this back to having Students and semester?

Pedagogy_gls <- gls(model= Final ~ Exam1 + Exam2 + Exam3 + HW + Quiz, data= data, weights=varFixed(~1/NStudents), method="ML")

summary(Pedagogy_gls)

# summary(Pedagogy_gls)$r.squared
#Rsquared doesn't work with heteroskedastic models
# sigma-6.95417

# summary(Pedagogy_gls)$tTable
# Pedagogy_gls$coefficients

# Pedagogy_gls$sigma
# coef(Pedagogy_gls$modelStruct, unconstrained=FALSE)

# summary(Pedagogy_gls)


data_copy$heteroskedastic_std_residuals <- resid(object=Pedagogy_gls, type="pearson")
data_copy$fittedVals <- fitted(Pedagogy_gls)

TSS <- sum((dataPreds$Final-mean(dataPreds$Final))^2)
ESS <- sum((dataPreds$Prediction-mean(dataPreds$Final))^2)
#R-squared value
ESS/TSS
```


# Section 3: Assumptions

### Linear
```{r, message = FALSE, out.width= "70%"}
library(car)
avPlots(Pedagogy_lm,ask=F)

cor(data$Exam1,data$Final)
cor(data$Exam2,data$Final)
cor(data$Exam3,data$Final)
cor(data$HW,data$Final)
cor(data$Quiz,data$Final)


```
* Looking at quantitative variables- approximately linear

### Independent

### Normal
```{r, message = FALSE, out.width= "50%"}
standard <- resid(object=Pedagogy_gls, type="pearson")
ggplot()+geom_histogram(mapping=aes(x=standard))
ks.test(standard, "pnorm")
```


```{r, message = FALSE, out.width= "50%"}
dataPreds <- predictgls(glsobj=Pedagogy_gls, level=.95, newdframe=data) 

ggplot() + 
geom_point(data=dataPreds, 
mapping=aes(x=Exam1, y=Final)) +  #Scatterplot 
geom_line(data=dataPreds, 
mapping=aes(x=Exam1, y=Prediction)) +  #Prediction Line 
geom_line(data=dataPreds, 
mapping=aes(x=Exam1, y=lwr), 
color="red", linetype="dashed") +  #lwr bound 
geom_line(data=dataPreds, 
mapping=aes(x=Exam1, y=upr), 
color="red", linetype="dashed")  #Upper bound


```




```{r, message = FALSE, out.width= "50%"}
dataPreds <- predictgls(glsobj=Pedagogy_gls, level=.95, newdframe=data) 

ggplot() + 
geom_point(data=dataPreds, 
mapping=aes(x=Exam2, y=Final)) +  #Scatterplot 
geom_line(data=dataPreds, 
mapping=aes(x=Exam2, y=Prediction)) +  #Prediction Line 
geom_line(data=dataPreds, 
mapping=aes(x=Exam2, y=lwr), 
color="red", linetype="dashed") +  #lwr bound 
geom_line(data=dataPreds, 
mapping=aes(x=Exam2, y=upr), 
color="red", linetype="dashed")  #Upper bound


```




```{r, message = FALSE, out.width= "50%"}
dataPreds <- predictgls(glsobj=Pedagogy_gls, level=.95, newdframe=data) 

ggplot() + 
geom_point(data=dataPreds, 
mapping=aes(x=Exam3, y=Final)) +  #Scatterplot 
geom_line(data=dataPreds, 
mapping=aes(x=Exam3, y=Prediction)) +  #Prediction Line 
geom_line(data=dataPreds, 
mapping=aes(x=Exam3, y=lwr), 
color="red", linetype="dashed") +  #lwr bound 
geom_line(data=dataPreds, 
mapping=aes(x=Exam3, y=upr), 
color="red", linetype="dashed")  #Upper bound


```



```{r, message = FALSE, out.width= "50%"}
dataPreds <- predictgls(glsobj=Pedagogy_gls, level=.95, newdframe=data) 

ggplot() + 
geom_point(data=dataPreds, 
mapping=aes(x=HW, y=Final)) +  #Scatterplot 
geom_line(data=dataPreds, 
mapping=aes(x=HW, y=Prediction)) +  #Prediction Line 
geom_line(data=dataPreds, 
mapping=aes(x=HW, y=lwr), 
color="red", linetype="dashed") +  #lwr bound 
geom_line(data=dataPreds, 
mapping=aes(x=HW, y=upr), 
color="red", linetype="dashed")  #Upper bound


```



```{r, message = FALSE, out.width= "50%"}
dataPreds <- predictgls(glsobj=Pedagogy_gls, level=.95, newdframe=data) 

ggplot() + 
geom_point(data=dataPreds, 
mapping=aes(x=Quiz, y=Final)) +  #Scatterplot 
geom_line(data=dataPreds, 
mapping=aes(x=Quiz, y=Prediction)) +  #Prediction Line 
geom_line(data=dataPreds, 
mapping=aes(x=Quiz, y=lwr), 
color="red", linetype="dashed") +  #lwr bound 
geom_line(data=dataPreds, 
mapping=aes(x=Quiz, y=upr), 
color="red", linetype="dashed")  #Upper bound


```
  
  
```{r}
plot(data$NStudents,data$Final)

```
  
  
  #cross validation
```{r}


# !!! fixme
n <- 30


# fix me


# predictgls(glsobj=glsobj, newdframe=data, level=.99)


data1 <- data[,c(2,3:8)]
n.cv <- 100 #Number of CV studies to run
n.test <- ceiling(n*.2)   #Number of observations in a test set


rpmse <- rep(x=NA, times=n.cv)
bias <- rep(x=NA, times=n.cv)
wid <- rep(x=NA, times=n.cv)
cvg <- rep(x=NA, times=n.cv)
for(cv in 1:n.cv){
  ## Select test observations
  test.obs <- sample(x=1:n, size=n.test)
  
  ## Split into test and training sets
  test.set <- data1[test.obs,]
  train.set <- data1[-test.obs,]
  
  ## Fit a gls() using the training data
  # train.lm <- lm(formula=BirthWeight ~ ., data=train.set)
  train.lm <-gls(model= Final ~ Exam1 + Exam2 + Exam3 + HW + Quiz, data= data, weights=varFixed(~1/NStudents), method="ML")
  
  
  ## Generate predictions for the test set
  # my.preds <- predict.lm(train.lm, newdata=test.set, interval="prediction")
  my.preds <- predictgls(glsobj=train.lm, newdframe=test.set, level=.95)

  ## Calculate bias
  bias[cv] <- mean(my.preds[,'Prediction']-test.set[['Final']])
  
  ## Calculate RPMSE
  rpmse[cv] <- (test.set[['Final']]-my.preds[,'Prediction'])^2 %>% mean() %>% sqrt()
  
  ## Calculate Coverage
  cvg[cv] <- ((test.set[['Final']] > my.preds[,'lwr']) & (test.set[['Final']] < my.preds[,'upr'])) %>% mean()
  
  ## Calculate Width
  wid[cv] <- (my.preds[,'upr'] - my.preds[,'lwr']) %>% mean()
  
}


plot(density(bias), main = "bias Density", xlab = "Values", col = "blue")
plot(density(rpmse), main = "rpmse Density ", xlab = "Values", col = "blue")
plot(density(cvg), main = "cvg Density", xlab = "Values", col = "blue")
plot(density(wid), main = "wid Density", xlab = "Values", col = "blue")

summary(bias)
summary(rpmse)
summary(cvg)
summary(wid)
```
  
  